
package bigws.todows;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.1
 * 
 */
@WebService(name = "ToDoWebService", targetNamespace = "http://ToDows.bigws/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ToDoWebService {


    /**
     * 
     * @param arg3
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "add", targetNamespace = "http://ToDows.bigws/", className = "bigws.todows.Add")
    @ResponseWrapper(localName = "addResponse", targetNamespace = "http://ToDows.bigws/", className = "bigws.todows.AddResponse")
    public String add(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        String arg3);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "delete", targetNamespace = "http://ToDows.bigws/", className = "bigws.todows.Delete")
    @ResponseWrapper(localName = "deleteResponse", targetNamespace = "http://ToDows.bigws/", className = "bigws.todows.DeleteResponse")
    public String delete(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @return
     *     returns bigws.todows.ListaTareas
     * @throws FileNotFoundException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "mostrar", targetNamespace = "http://ToDows.bigws/", className = "bigws.todows.Mostrar")
    @ResponseWrapper(localName = "mostrarResponse", targetNamespace = "http://ToDows.bigws/", className = "bigws.todows.MostrarResponse")
    public ListaTareas mostrar()
        throws FileNotFoundException_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns bigws.todows.ListaTareas
     * @throws FileNotFoundException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "buscar", targetNamespace = "http://ToDows.bigws/", className = "bigws.todows.Buscar")
    @ResponseWrapper(localName = "buscarResponse", targetNamespace = "http://ToDows.bigws/", className = "bigws.todows.BuscarResponse")
    public ListaTareas buscar(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0)
        throws FileNotFoundException_Exception
    ;

}
